{
    'name': 'Visual Relationship Map',
    'version': '18.0.1.0.0',
    'summary': 'Interactive Visual Document Flowchart. Effortlessly track and visualize relationships between Sales, Purchases, Inventory, and Invoices in one unified map.',
    'author': 'FoxPink',
    'website': 'https://foxpink.netlify.app/',
    'category': 'Sales/Sales',
    'license': 'OPL-1',
    'price': 49.00,
    'currency': 'USD',
    'depends': ['web', 'sale_management', 'stock', 'account', 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        'views/visual_map_actions.xml',
        'views/sale_order_views.xml',
        'views/res_config_settings_view.xml',
        'views/visual_map_config_view.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'visual_relationship_map/static/lib/mermaid.min.js',
            'visual_relationship_map/static/src/css/visual_map.css',
            'visual_relationship_map/static/src/js/visual_map_dialog.js',
            'visual_relationship_map/static/src/xml/visual_map_dialog.xml',
        ],
    },
    'images': [
        'static/description/banner.png',
        'static/description/icon.png',
        'static/description/overview.png',
        'static/description/ui_sales_order_flow.png',
        'static/description/ui_purchase_order_flow.png',
        'static/description/ui_picking_flow.png',
        'static/description/ui_invoice_flow.png',
        'static/description/ui_tooltip_zoom.png',
        'static/description/ui_settings.png',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
